export const ADICIONA_PROJETO = "ADICIONA_PROJETO";
export const ATUALIZA_PROJETO = "ATUALIZA_PROJETO";
export const EXCLUIR_PROJETO = "EXCLUIR_PROJETO";
export const DEFINIR_PROJETOS = "DEFINIR_PROJETOS";

export const NOTIFICAR = "NOTIFICAR";
